### ISSUE TITLE
用playwright库不用代理么

### ISSUE THREAD

**Issue by SaucePlum** [SuperKuroko/Mitsusa-Robot#1]

**Comment by SuperKuroko** [comment]
不用的哦

**Comment by SaucePlum** [comment]
这边发现一个httpx.ConnectTimeout问题会终止程序运行, 看一下??

**Comment by SuperKuroko** [comment]
是哪个part的连接错误，以及win还是linux系统？

**Comment by SaucePlum** [comment]
win



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 22, 2022 11:39 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [SuperKuroko/Mitsusa-Robot] 用playwright库不用代理么 (Issue #1)




 
是哪个part的连接错误，以及win还是linux系统？
